# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'whole.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(905, 489)
        self.labInputID_9 = QtWidgets.QLabel(Form)
        self.labInputID_9.setGeometry(QtCore.QRect(940, 60, 61, 34))
        self.labInputID_9.setText("")
        self.labInputID_9.setObjectName("labInputID_9")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(30, 10, 840, 467))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.labInputFile = QtWidgets.QLabel(self.widget)
        self.labInputFile.setObjectName("labInputFile")
        self.gridLayout.addWidget(self.labInputFile, 0, 0, 1, 3)
        self.openet = QtWidgets.QLineEdit(self.widget)
        self.openet.setObjectName("openet")
        self.gridLayout.addWidget(self.openet, 0, 3, 1, 1)
        self.openbtn = QtWidgets.QPushButton(self.widget)
        self.openbtn.setObjectName("openbtn")
        self.gridLayout.addWidget(self.openbtn, 0, 4, 1, 1)
        self.appbtn = QtWidgets.QPushButton(self.widget)
        self.appbtn.setObjectName("appbtn")
        self.gridLayout.addWidget(self.appbtn, 1, 3, 1, 1)
        self.appbtn_2 = QtWidgets.QPushButton(self.widget)
        self.appbtn_2.setObjectName("appbtn_2")
        self.gridLayout.addWidget(self.appbtn_2, 1, 6, 1, 1)
        self.labInputFile_3 = QtWidgets.QLabel(self.widget)
        self.labInputFile_3.setText("")
        self.labInputFile_3.setObjectName("labInputFile_3")
        self.gridLayout.addWidget(self.labInputFile_3, 1, 7, 1, 1)
        self.labInputID_3 = QtWidgets.QLabel(self.widget)
        self.labInputID_3.setObjectName("labInputID_3")
        self.gridLayout.addWidget(self.labInputID_3, 2, 0, 1, 1)
        self.orderet = QtWidgets.QLineEdit(self.widget)
        self.orderet.setObjectName("orderet")
        self.gridLayout.addWidget(self.orderet, 2, 1, 1, 3)
        self.labInputID = QtWidgets.QLabel(self.widget)
        self.labInputID.setObjectName("labInputID")
        self.gridLayout.addWidget(self.labInputID, 2, 5, 1, 1)
        self.etid = QtWidgets.QLineEdit(self.widget)
        self.etid.setObjectName("etid")
        self.gridLayout.addWidget(self.etid, 2, 6, 1, 2)
        self.insbtn = QtWidgets.QPushButton(self.widget)
        self.insbtn.setObjectName("insbtn")
        self.gridLayout.addWidget(self.insbtn, 2, 8, 1, 1)
        self.labInputID_4 = QtWidgets.QLabel(self.widget)
        self.labInputID_4.setObjectName("labInputID_4")
        self.gridLayout.addWidget(self.labInputID_4, 3, 0, 1, 1)
        self.timeet = QtWidgets.QLineEdit(self.widget)
        self.timeet.setObjectName("timeet")
        self.gridLayout.addWidget(self.timeet, 3, 1, 1, 3)
        self.ettext = QtWidgets.QTextEdit(self.widget)
        self.ettext.setObjectName("ettext")
        self.gridLayout.addWidget(self.ettext, 3, 6, 4, 2)
        self.labInputID_5 = QtWidgets.QLabel(self.widget)
        self.labInputID_5.setObjectName("labInputID_5")
        self.gridLayout.addWidget(self.labInputID_5, 4, 0, 1, 1)
        self.zhutiet = QtWidgets.QLineEdit(self.widget)
        self.zhutiet.setObjectName("zhutiet")
        self.gridLayout.addWidget(self.zhutiet, 4, 1, 1, 3)
        self.labInputID_2 = QtWidgets.QLabel(self.widget)
        self.labInputID_2.setObjectName("labInputID_2")
        self.gridLayout.addWidget(self.labInputID_2, 4, 5, 1, 1)
        self.labInputID_6 = QtWidgets.QLabel(self.widget)
        self.labInputID_6.setObjectName("labInputID_6")
        self.gridLayout.addWidget(self.labInputID_6, 5, 0, 1, 1)
        self.placeet = QtWidgets.QLineEdit(self.widget)
        self.placeet.setObjectName("placeet")
        self.gridLayout.addWidget(self.placeet, 5, 1, 1, 3)
        self.labInputID_8 = QtWidgets.QLabel(self.widget)
        self.labInputID_8.setObjectName("labInputID_8")
        self.gridLayout.addWidget(self.labInputID_8, 6, 0, 1, 1)
        self.ketitext = QtWidgets.QTextEdit(self.widget)
        self.ketitext.setObjectName("ketitext")
        self.gridLayout.addWidget(self.ketitext, 6, 1, 1, 3)
        self.labInputID_10 = QtWidgets.QLabel(self.widget)
        self.labInputID_10.setObjectName("labInputID_10")
        self.gridLayout.addWidget(self.labInputID_10, 7, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 7, 6, 2, 2)
        self.labInputID_7 = QtWidgets.QLabel(self.widget)
        self.labInputID_7.setObjectName("labInputID_7")
        self.gridLayout.addWidget(self.labInputID_7, 8, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 8, 2, 1, 2)
        self.labInputFile_2 = QtWidgets.QLabel(self.widget)
        self.labInputFile_2.setObjectName("labInputFile_2")
        self.gridLayout.addWidget(self.labInputFile_2, 9, 0, 1, 2)
        self.Slider = QtWidgets.QSlider(self.widget)
        self.Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Slider.setObjectName("Slider")
        self.gridLayout.addWidget(self.Slider, 9, 3, 1, 6)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labInputFile.setText(_translate("Form", "请输入文件："))
        self.openbtn.setText(_translate("Form", "添加文件"))
        self.appbtn.setText(_translate("Form", "显示模块"))
        self.appbtn_2.setText(_translate("Form", "查询模块"))
        self.labInputID_3.setText(_translate("Form", "序号"))
        self.labInputID.setText(_translate("Form", "请输入序号"))
        self.insbtn.setText(_translate("Form", "查询"))
        self.labInputID_4.setText(_translate("Form", "时间"))
        self.labInputID_5.setText(_translate("Form", "主体"))
        self.labInputID_2.setText(_translate("Form", "事件描述"))
        self.labInputID_6.setText(_translate("Form", "地点"))
        self.labInputID_8.setText(_translate("Form", "客体"))
        self.labInputID_10.setText(_translate("Form", "图片"))
        self.labInputID_7.setText(_translate("Form", "图片"))
        self.labInputFile_2.setText(_translate("Form", "序列号"))
